### ISSUE TITLE
Update build C++ workflow to use `macos-latest`

### ISSUE THREAD

**Issue by drewoldag** [lephare-photoz/lephare#102]
We noticed that the C++ build CI test started failing unexpectedly. This was a result of the runner image alias, `macos-latest` being migrated from representing `macos-12` to `macos-14`. This migration was documented here: https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/

The question at hand is whether we should replace the existing `macos-14` runner image in the C++ build CI with macos-latest, with the understanding that doing so will allow us to continue to test newer version of macos without having to modify the CI. 

The downside is that things may break without warning when the `-latest` alias is updated, causing confusion. The upside is that less attention will need to be devoted to watching for newer versions of macos that need to be built against.

Ultimately this is a question for the long term maintainers of the software.

**Comment by drewoldag** [comment]
Also this for reference: https://github.com/actions/runner-images?tab=readme-ov-file

**Comment by johannct** [comment]
As I mentioned in the past, I consider the CI as the cornerstone to any claim that LePHARE has been successfully built and testes on a set of OS config. As such, -latest does not fit the bill, as it does not refer to a definite system. I would be in favor of not using it. It is the maintainers' duty to check new OS, possibly based on request from the community or internal needs during dev phases.
