### ISSUE TITLE
Look into pytest env variables

### ISSUE THREAD

**Issue by OliviaLynn** [lephare-photoz/lephare#111]
We've been having trouble where environmental variables that are theoretically set in conf.py don't fully work in tests, which is remedied by explicitly setting them within the test. Not great that we have to do this.

Also, we may not want them to be so conditionally set in tests (with the ifs), this is worth taking a big picture look at as well.

**Comment by OliviaLynn** [comment]
Drew added a nice set_env_vars fixture, so I'll go through the unit tests to implement this throughout for consistency

**Comment by raphaelshirley** [comment]
We now simply always set them to make sure local tests aren't using local directories.
