### ISSUE TITLE
RFC : Path to building the final documentation structure

### ISSUE THREAD

**Issue by johannct** [lephare-photoz/lephare#166]
It is agreed upon that the documentation will be deployed in readthedocs. An example pointed at by the LINCC team is [sorcha](https://sorcha.readthedocs.io/en/latest/index.html#). The first point to notice is that the github README is minimalistic, defining what sorcha is and who is contributing. A link to the readthedocs documentation is provided. 

If agreed, I propose that we go this route. 

Next, we may want to flesh out the TOC, so that afterwards we can create one branch per page. Inspired by it, a first stab at it can be: 

```
  page index : definition, citation, support, acknowledgements,  troubleshooting, release
   installation #including uninstall
   overview
   Keywords <keywords>
   gettingstarted # running the legacy way
   using the python interface
   notebooks
   contributors # perhaps using https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-a-projects-contributors for github contributors
   C API Reference <doxygen_output/c_lib/library_root>
   Python API Reference <autoapi/index>
```

Is this a workable start?

**Comment by raphaelshirley** [comment]
The first page needs some work to lead different users to the correct starting point. I broadly identify three typical users:

1. Completely new to LePHARE. We want to direct these users to python doucmentation and the example notebooks.
2. Previous users of LePHARE. We want to direct these to documentation on the command line executables and explain they are present after pip install lephare.
3. Developers. We want to direct them to a local installation instructions.

I think we do need to introduce the lephare_data repository quite early. I was using the COSMOS example with the automatic downloading as an example. We should maybe mention that the full repository can also be git cloned to ensure everything is present.

The original documentation might be more for presenting the way the algorithms actually work and describing the physics. Quite a bit of the original documentation will need to be moved around a bit. But perhaps the bulk could come under a heading such as Algorithm Details.

Perhaps the documentation is also a place for the contributions. At present I already have the original front page from the docuementation but perhaps we should have a whole page with contributions and key citations.

**Comment by johannct** [comment]
From the whiteboard:

Overview JCT
 - general structure of the code, philosophy
 - Nice overview figure of the structure
Install the code RS
- pip install lephare and test it with simple notebook
- install external and environement
- install for developers
Run with notebooks: point to notebooks, explannation, what keys are doing
Run with notebooks: point to notebook, esplanation, what key are doing
Run with command line (legacy)
OI:
Keyword: input and output
Detailed documentation

For developerss JCT
unit testing
C API
Py API
contribution

**Comment by raphaelshirley** [comment]
Olivier and I just met. We iterated on this and came up with:

- Overview
- Getting Started
  - pip install
  - Basic usage notebook
  - Basic physical parameter example
- Advanced usage using Python interface
  - All the notebooks
  - How to add new attenuation curve
- Command line interface
  - Cloning lephare-data
  - Example with readme_full
- Keywords
- Detailed documentation
- Developer install
- Python API
- C API

**Comment by johannct** [comment]
I believe this can be closed @raphaelshirley

**Comment by johannct** [comment]
closing as all this is now captured in the doc
