### ISSUE TITLE
Fixing a few minor doc/web page incongruities

### ISSUE THREAD

**Issue by johannct** [lephare-photoz/lephare#186]
On the github page : 
- fix linguistic-doc finding PureBasic and sed languages

On pypi page : 
- fix email Johann/Stéphane mismatch. If this has to appear, it should be Olivier.
- fix github link to directly point to lephare-photoz/lephare instead of the former lincc-framework space.
- setup.py is now deprecated and should be removed from the root dir.

**Comment by johannct** [comment]
being fixed in #187

**Comment by johannct** [comment]
I did not find yet where the name/email mismatch on PYPI is coming from.... @drewoldag perhaps?

**Comment by drewoldag** [comment]
Hi @johannct the best guess at this point is that the `author` field in setup.py is being picked up and added to PKG-INFO (which is then likely used to populate the Meta section of the PyPI page). I would assume that when you remove the setup.py file, that the first author will be picked up from the `authors` list in `pyproject.toml`. 

I tested this locally on a not-lephare project, and was able to reproduce the behavior when I added a dummy setup.py file. Without this file, ther PKG-INFO includes only a `author-email` field, which hopefully would be interpreted correctly by PyPI. 

You could try removing (or renaming) setup.py locally and then run `pipx run build --sdist`. You should then be able to examine the PKG-INFO file that is produced. The hypothesis is that the author-emails listed in PKG-INFO would be the same as those listed in pyproject.toml.

**Comment by johannct** [comment]
thanks @drewoldag , looks like your hint is spot on!

**Comment by johannct** [comment]
fixed in #187
