### ISSUE TITLE
Remove soon to be defunct macos-12 builds

### ISSUE THREAD

**Issue by raphaelshirley** [lephare-photoz/lephare#222]
Apparently the macos-12 runner will be removed

https://github.com/s3fs-fuse/s3fs-fuse/issues/2552

I can see macos-12 in 

https://github.com/lephare-photoz/lephare/blob/main/.github/workflows/publish-to-pypi.yml
https://github.com/lephare-photoz/lephare/blob/main/.github/workflows/testing-mac-only.yml
https://github.com/lephare-photoz/lephare/blob/main/.github/workflows/compile-cpp.yml

Shall we delete?, replace with macos-13 or macos-latest?

I think we may have prevously had issues with latest.

**Comment by johannct** [comment]
Go for macos-13 then. ubuntu on the other hand could be latest everywhere, I believe, but let's leave that aside for now

**Comment by raphaelshirley** [comment]
I seem to remember a discussion with @drewoldag about not using 'latest' on perhaps ubuntu or mac but I can't remember why we rejected it. I think it kept introducing breaking changes?

**Comment by drewoldag** [comment]
My memory is that using `latest` will just mean that things might change without you being aware of it. So under the hood latest may change (e.g. from 13 to 14) and break. If that happens and it breaks something it is very challenging to determine why. From your perspective nothing changed, and github isn't great about advertising those kinds of changes. 

So macos-13 should be fine. 

Here's the current list of hosted runners available: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

**Comment by johannct** [comment]
yes agreed.
