### ISSUE TITLE
The header of the output of mag_gal -t S (previous mag_star in Fortran) is wrong

### ISSUE THREAD

**Issue by Mara2016** [lephare-photoz/lephare#241]
When running mag_gal -t S, we realised that the header (and maybe the content?) is not what it should be. For STARS usually the  name of the fllters should be listed. Currently, the header is the same as that from mag_gal -t G.

**Comment by raphaelshirley** [comment]
Even for galaxies it would be preferable to have the actual filter names in the heading rather than just the name of the vector and a number of names which does not correspond to the columns

**Comment by johannct** [comment]
we do not have filter name convention in LePHARE. We just have a file path, and an ordinal number.

**Comment by johannct** [comment]
we can add the sequence of file paths once inside de ascii file, before the column names
