### ISSUE TITLE
Review the way that environment variables are being used

### ISSUE THREAD

**Issue by drewoldag** [lephare-photoz/lephare#32]
We should take a moment to determine:

- whether the environment variables `LEPHAREDIR` and `LEPHAREWORK` are doing what we want
- whether there is a reasonable way that we can set defaults but still let the user modify them
- whether these are the only two we need. Note that `LEPHARE` dir is used for at least two distinct purposes.
- ???

**Comment by johannct** [comment]
Currently unit testing does not trigger execution that outputs anything into LEPHAREWORK, if I am not mistaken. Nevertheless, to be on the safe side for later, I would advocate for a "WORK" dir inside tests, where the unit tests live, that needs to be deleted by the CI unit testing trigger (I am not expecting that we would need to examine these)

**Comment by johannct** [comment]
LEPHAREDIR default should be the root directory for anything related to github and its actions, as in this case the usual source code repo structure is preserved. This will mean that if the big datafile is to be downloaded and cached by github actions in the future, it should be installed at the root directory, as it is in the gitlab repo.

**Comment by johannct** [comment]
but yes, let's try to break the code :)

**Comment by drewoldag** [comment]
@johannct plans to work on this while in Seattle

**Comment by raphaelshirley** [comment]
As I mentioned on the Slack I think we need a solution for pip installed version where there is no source directory. We could add a required input to all functions that need one of the two directories and possibly merge them into one? Perhaps timestamping outputs could also add some safety.

**Comment by raphaelshirley** [comment]
An example could be the butler in the LSST Science pipelines where there is an object associated with the repo.

```
import lephare as lp
lephare_data = lp.make_data_repo('./path/to/repo/DATA')
lephare_data.get_auxialiary_files('./path/to/params/lsst.para') #loads para and gets filters and templates using pooch and puts them in repo
lp.some_function_that_makes_output(lephare_data.path()) #gets path from repo object
```

**Comment by drewoldag** [comment]
Yeah, this seems very reasonable to me. We can fall back to the default OS cache if the user doesn't provide a path when they create the `lephare_data` object, as in `lp.make_data_repo()`

**Comment by raphaelshirley** [comment]
Looking into the c++ code I see that it depends on the environment variables. I also think that there are some key requirements going forward:

1. Those people that are using the c++ binaries with the environment variables pointing to LEPHAREDIR for auxiliary files and LEPHAREWORK for intermediate files must be able to continue to do so. This can be achieved by checking if the environment variables are set during import lephare and creating a default location in the cache if not.
2. Those that use pip install lephare should be able to import lephare without setting the environment variables and have everything 'just work' without worrying about where to put the files.
3. It must be possible to make new runs and refer back to previous runs. This can probably be best be achieved using timestamped directories for the intermediate files as described in the pseudocode above.

**Comment by OliviaLynn** [comment]
So far we've settled on using the environmental variables as they are, but allow the user to override them if desired (related #50, #63)
