### ISSUE TITLE
Change the way *.list files are used so that they don't need to be placed in specific directories

### ISSUE THREAD

**Issue by drewoldag** [lephare-photoz/lephare#48]
Currently *.list files need to be placed in specific directories, and the file paths defined in the .list file is relative to it's current directory. 

It would be convenient for *.list files to provide the path relative the the LEPHAREDIR path. 

i.e. if LEPHAREDIR = "~/Library/Caches/lephare/data"
then the list file: `sed/QSO/QSO_MOD.list` would contain entries like:
```
sed/QSO/qso_template_norm.sed	
sed/QSO/qso_low_template_norm.sed	
sed/QSO/qso_high_template_norm.sed
sed/QSO/QSO_SDSS.sed
sed/QSO/QSO_Cristiani.sed
```

This would allow users to store their list files in any convenient location, and would allow the inclusion of additional data files in lists that are not stored in the default data structure (`sed/QSO/` in this case)

**Comment by raphaelshirley** [comment]
Just to summarise our discussion earlier... I think that the sed lists assume paths relative to the type directory so if sedtolib is run with type QSO lephare assumes the files are with respect to sed/QSO regardless of the list's location. I think this assumption may be hardcoded into the c++ so we may want to just close this issue without doing anything.

If we don't want to do that the two alternatives are to assume lists are relative to top level as you recommend or to assume relative to the location of the list which breaks some examples at present.

**Comment by johannct** [comment]
I am in favor of absolute paths everywhere. But it might be something to deal with later.

**Comment by OliviaLynn** [comment]
Potentially in the interim, we could implement some helper functions to convert these files between relative and absolute paths
