### ISSUE TITLE
Add checks on file inputs to print errors without crashing the kernel

### ISSUE THREAD

**Issue by raphaelshirley** [lephare-photoz/lephare#52]
**Bug report**

import lephare as lp
keymap=lp.read_config("$LEPHAREDIR/examples/COSMOS.para")
sedlib = lp.Sedtolib(config_keymap=keymap)
sedlib.run(typ="STAR", star_sed="file_path_doesnt_exit.list")

Crashes kernel without error if "file_path_doesnt_exit.list" does not point to an actual file.

I think we should just add a check that the file exists and throw an error if not.

**Before submitting**
Please check the following:

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [x] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [x] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by johannct** [comment]
I am not sure the first line is going to be ok @raphaelshirley . The function read_config in keyword.cpp does not expand env variables.

**Comment by johannct** [comment]
there is a check.... The problem is that the notebook seems to go on....

**Comment by johannct** [comment]
do we have more input on this issue? @raphaelshirley ?

**Comment by raphaelshirley** [comment]
I noticed that Iary noted a similar issue in the overleaf modifications txt:

"The code doesn't stop when an input file (eg GAL_LIB_IN) is not existing. Need to add a sanity check otherwise the user will get a seg-fault error without understanding why."

Another example is for instance lephare.PhotoZ.build_output_tables which can take para_out=None in which case it uses the config value which may not exist.

the simplest solution seems to me to simply check the file exists python side. We could run a check on the config file to ensure all input files exist.

I think all of the examples involve the Runner class. Could we modify that to check inputs exist? The problem is that config values can be overridden after initialisation.

Another option would be to give the Runner class a check_config_inputs every time run is called?

**Comment by raphaelshirley** [comment]
Just copying some fo the discussion from Slack here. I think we should add something like:

```
if (!file.is_open()) {
        throw std::runtime_error("Unable to open file: " + filename);
    }
```

after every instance of ifstream or open in the c++

**Comment by raphaelshirley** [comment]
In the particular example above I realised that in my conda environment with lephare installed from PyPI it actually is throwing an exception as expected from https://github.com/lephare-photoz/lephare/blob/main/src/lib/SEDLib.h#L242

But causing a segmentation fault when called from locally installed lephare using the dev installation guide.

In addition to that some exceptions are thrown correctly. For instance:

```
import lephare as lp
keymap=lp.read_config("file_does_not_exist.para")
```

Does correctly throw an exception.

I can not find an example in the c++ code where there is no test and `throw invalid_argument` called.

**Comment by raphaelshirley** [comment]
Further more installing clang compilers using 

conda install -c conda-forge cxx-compiler

rather than the gnu compilers which were set in my environment variables fixed the issue on my mac.

**Comment by raphaelshirley** [comment]
We will probably close this issue and accept that it was caused by gnu compiler issues on mac.
