### ISSUE TITLE
Consolidate the "informer" steps of Lephare into a single function

### ISSUE THREAD

**Issue by drewoldag** [lephare-photoz/lephare#74]
Most users likely won't want to run the three non-estimation steps separately, and as an example in rail_lephare, these three steps are merged under the hood of the `inform` stage. 

We should consider making a wrapper in lephare (that could also be used in the rail_lephare inform stage) that executes `FiltSvc`, `SedToLib`, and `MagGal` and requires only one function call.

**Comment by OliviaLynn** [comment]
Related to #74

**Comment by raphaelshirley** [comment]
Further to the discussion yesterday I think what we want can be achieved with the current config settings but adding in the possibility of overwriting for stars, galaxies or agn so from rail lephare we can likewise just have four parameters the base config and then three overwrite possibilities.

```
def inform(config, star_config=None, gal_config=None, qso_config=None):
    """"Runs filter, sedtolib, and mag_gal for all three types with optional overwrides"""
```

**Comment by raphaelshirley** [comment]
In pseudo code I am working on a pair of abstract functions that would allow a full run to be conducted with something like:

```
import lephare as lp
from astropy.table import Table
config=lp.read_config('./data/COSMOS.para')
lp.prepare(config)
input=Table.read('./data/input.fits')
output=lp.process(config,input)
```

**Comment by raphaelshirley** [comment]
Or perhaps it should not take an input catalogue but rather id,flux,eflux,context,zspec,string_input otherwise the input table will have to have a particular structure or column names.
