### ISSUE TITLE
Ensure that a single config file can fully represent the configuration for a complete lephare run

### ISSUE THREAD

**Issue by drewoldag** [lephare-photoz/lephare#75]
Specifically overwriting EXTINCT_LAW for different objects shouldn't be required. But we should also take the opportunity to audit the config to ensure that we can fully specify the parameters for a full run of lephare in a single file. 

This would also be beneficial for tracking results, as we could then copy the config file into the runs/<timestamped_run> directory.

**Comment by raphaelshirley** [comment]
This would also allow the filter, sedtolib, and maggal commands to be abstracted to a single function that runs all with a given config file. this would also simplify the rail_lephare inform code and parameters.

**Comment by drewoldag** [comment]
Yes, we can have a single config file (yaml) that is passed to the python interface. The python interface would then pass the parameters to the C++ code. 

We would move away from a .para file entirely, and still have only one configuration file.

**Comment by drewoldag** [comment]
The way this is working in RAIL is fine for now. Going to close as won't do.
