### ISSUE TITLE
data retriever making directories for no reason

### ISSUE THREAD

**Issue by raphaelshirley** [lephare-photoz/lephare#78]
When I call lephare.data_retrieval.get_auxiliary_data() it makes a series of directories for no reason. I think these may be made by lephare.data_retrieval._create_directories_from_files(). Is it because it needs to be doing this in the LEPHAREWORK directory?

**Before submitting**
Please check the following:

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [x] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [x] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by OliviaLynn** [comment]
Some notes while I work on this:
- [ ] get_auxillary_data is using the DEFAULT_BASE_URL (https://raw.githubusercontent.com/lephare-photoz/lephare-data/main/) to clone the repo, while we need the repo url https://github.com/lephare-photoz/lephare-data. Honestly, maybe what we really need is some kind of clone_repo method in the data retrieval module
