### ISSUE TITLE
Create abstract photoz runner

### ISSUE THREAD

**Issue by raphaelshirley** [lephare-photoz/lephare#97]
Currently running the photoz involves reading in a source for every object, looping over it and performing various functions. We would like to create a higher level more abstract Runner based method. This should be able to be called with 

from lephare import photoZRunner

`output = photoZRunner(config, ids, fluxes, efluxes, context, zspec)`

which gives an astropy table output. We might want to make ids,context,zspec optional and have a default output.para file for specifying the output columns.

This would allow the full run to be conducted with two lines

**Before submitting**
Please check the following:

- [x] I have described the purpose of the suggested change, specifying what I need the enhancement to accomplish, i.e. what problem it solves.
- [x] I have included any relevant links, screenshots, environment information, and data relevant to implementing the requested feature, as well as pseudocode for how I want to access the new functionality.
- [x] If I have ideas for how the new feature could be implemented, I have provided explanations and/or pseudocode and/or task lists for the steps.

**Comment by raphaelshirley** [comment]
This overlaps with the ZPhota class in src/lephare/zphota.py

Should I be modifying that? As far as I know we don't currently have an example calling that class which seems to be making a python command line equivalent of zphota.

**Comment by johannct** [comment]
ok, so zphota.py is a script. The class in there inherits from Runner and is supposed to be used in the script to mimic the C++ executable. It can certainly be used standalone and exercized within the sequence of python calls but it was not its main purpose initially. You are welcome to modify it but it needs to continue to mimic the C++ executable
