### ISSUE TITLE
Add original pdf documentation to the docs

### ISSUE THREAD

**Issue by raphaelshirley** [lephare-photoz/lephare#99]
We probably want to include the original documentation for command line running. This may be superseeded but for now we just want to add it to github and link to it from the main sphinx documentation:

https://gitlab.lam.fr/Galaxies/LEPHARE/-/blob/master/doc/LePhare_documentation.pdf?ref_type=heads

**Comment by johannct** [comment]
we can also build it from the latex

**Comment by raphaelshirley** [comment]
Ok, as far as I am aware the latex isn't publicly available can you send it to me and I'll start a PR?

**Comment by johannct** [comment]
I think it was developed on overleaf, no? https://www.overleaf.com/project/5babcda8dbea747e1da1a6e0 : right?

**Comment by raphaelshirley** [comment]
That sounds correct but I don't have permissions on that project can you send me an invite?
